Level up to a version of common http which uses less EntityUtils methods and is consistent with bus client.
Caused by: java.lang.NoSuchMethodError: org.apache.http.util.EntityUtils.consume
at uk.co.eelpieconsulting.common.http.HttpFetcher.executeRequestAndReadResponseBody(HttpFetcher.java:75)
at uk.co.eelpieconsulting.common.http.HttpFetcher.get(HttpFetcher.java:55)
at uk.co.eelpieconsulting.buses.client.BusesClient.getMultipleStopMessages(BusesClient.java:85)